// Generated by gencpp from file ric_board/calibIMU.msg
// DO NOT EDIT!


#ifndef RIC_BOARD_MESSAGE_CALIBIMU_H
#define RIC_BOARD_MESSAGE_CALIBIMU_H

#include <ros/service_traits.h>


#include <ric_board/calibIMURequest.h>
#include <ric_board/calibIMUResponse.h>


namespace ric_board
{

struct calibIMU
{

typedef calibIMURequest Request;
typedef calibIMUResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct calibIMU
} // namespace ric_board


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::ric_board::calibIMU > {
  static const char* value()
  {
    return "6968a03825da206ec312ec452ae9bac4";
  }

  static const char* value(const ::ric_board::calibIMU&) { return value(); }
};

template<>
struct DataType< ::ric_board::calibIMU > {
  static const char* value()
  {
    return "ric_board/calibIMU";
  }

  static const char* value(const ::ric_board::calibIMU&) { return value(); }
};


// service_traits::MD5Sum< ::ric_board::calibIMURequest> should match 
// service_traits::MD5Sum< ::ric_board::calibIMU > 
template<>
struct MD5Sum< ::ric_board::calibIMURequest>
{
  static const char* value()
  {
    return MD5Sum< ::ric_board::calibIMU >::value();
  }
  static const char* value(const ::ric_board::calibIMURequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::ric_board::calibIMURequest> should match 
// service_traits::DataType< ::ric_board::calibIMU > 
template<>
struct DataType< ::ric_board::calibIMURequest>
{
  static const char* value()
  {
    return DataType< ::ric_board::calibIMU >::value();
  }
  static const char* value(const ::ric_board::calibIMURequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::ric_board::calibIMUResponse> should match 
// service_traits::MD5Sum< ::ric_board::calibIMU > 
template<>
struct MD5Sum< ::ric_board::calibIMUResponse>
{
  static const char* value()
  {
    return MD5Sum< ::ric_board::calibIMU >::value();
  }
  static const char* value(const ::ric_board::calibIMUResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::ric_board::calibIMUResponse> should match 
// service_traits::DataType< ::ric_board::calibIMU > 
template<>
struct DataType< ::ric_board::calibIMUResponse>
{
  static const char* value()
  {
    return DataType< ::ric_board::calibIMU >::value();
  }
  static const char* value(const ::ric_board::calibIMUResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // RIC_BOARD_MESSAGE_CALIBIMU_H
