// Generated by gencpp from file ric_board/DevStatus.msg
// DO NOT EDIT!


#ifndef RIC_BOARD_MESSAGE_DEVSTATUS_H
#define RIC_BOARD_MESSAGE_DEVSTATUS_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace ric_board
{
template <class ContainerAllocator>
struct DevStatus_
{
  typedef DevStatus_<ContainerAllocator> Type;

  DevStatus_()
    : devName()
    , type(0)
    , values()  {
    }
  DevStatus_(const ContainerAllocator& _alloc)
    : devName(_alloc)
    , type(0)
    , values(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _devName_type;
  _devName_type devName;

   typedef int8_t _type_type;
  _type_type type;

   typedef std::vector<float, typename ContainerAllocator::template rebind<float>::other >  _values_type;
  _values_type values;




  typedef boost::shared_ptr< ::ric_board::DevStatus_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ric_board::DevStatus_<ContainerAllocator> const> ConstPtr;

}; // struct DevStatus_

typedef ::ric_board::DevStatus_<std::allocator<void> > DevStatus;

typedef boost::shared_ptr< ::ric_board::DevStatus > DevStatusPtr;
typedef boost::shared_ptr< ::ric_board::DevStatus const> DevStatusConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ric_board::DevStatus_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ric_board::DevStatus_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace ric_board

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'sensor_msgs': ['/opt/ros/indigo/share/sensor_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/indigo/share/geometry_msgs/cmake/../msg'], 'ric_board': ['/home/cc/ee106a/fa17/class/ee106a-aax/ros_workspaces/project/src/ric/ric_board/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::ric_board::DevStatus_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ric_board::DevStatus_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ric_board::DevStatus_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ric_board::DevStatus_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ric_board::DevStatus_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ric_board::DevStatus_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ric_board::DevStatus_<ContainerAllocator> >
{
  static const char* value()
  {
    return "636f4230c331f41de9571d397f5f8f9a";
  }

  static const char* value(const ::ric_board::DevStatus_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x636f4230c331f41dULL;
  static const uint64_t static_value2 = 0xe9571d397f5f8f9aULL;
};

template<class ContainerAllocator>
struct DataType< ::ric_board::DevStatus_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ric_board/DevStatus";
  }

  static const char* value(const ::ric_board::DevStatus_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ric_board::DevStatus_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string devName\n\
int8 type\n\
float32[] values\n\
\n\
";
  }

  static const char* value(const ::ric_board::DevStatus_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ric_board::DevStatus_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.devName);
      stream.next(m.type);
      stream.next(m.values);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct DevStatus_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ric_board::DevStatus_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ric_board::DevStatus_<ContainerAllocator>& v)
  {
    s << indent << "devName: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.devName);
    s << indent << "type: ";
    Printer<int8_t>::stream(s, indent + "  ", v.type);
    s << indent << "values[]" << std::endl;
    for (size_t i = 0; i < v.values.size(); ++i)
    {
      s << indent << "  values[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.values[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // RIC_BOARD_MESSAGE_DEVSTATUS_H
