// Generated by gencpp from file ric_board/get_devs.msg
// DO NOT EDIT!


#ifndef RIC_BOARD_MESSAGE_GET_DEVS_H
#define RIC_BOARD_MESSAGE_GET_DEVS_H

#include <ros/service_traits.h>


#include <ric_board/get_devsRequest.h>
#include <ric_board/get_devsResponse.h>


namespace ric_board
{

struct get_devs
{

typedef get_devsRequest Request;
typedef get_devsResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct get_devs
} // namespace ric_board


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::ric_board::get_devs > {
  static const char* value()
  {
    return "b7af88b185ed99adc5cd1d5346afef5c";
  }

  static const char* value(const ::ric_board::get_devs&) { return value(); }
};

template<>
struct DataType< ::ric_board::get_devs > {
  static const char* value()
  {
    return "ric_board/get_devs";
  }

  static const char* value(const ::ric_board::get_devs&) { return value(); }
};


// service_traits::MD5Sum< ::ric_board::get_devsRequest> should match 
// service_traits::MD5Sum< ::ric_board::get_devs > 
template<>
struct MD5Sum< ::ric_board::get_devsRequest>
{
  static const char* value()
  {
    return MD5Sum< ::ric_board::get_devs >::value();
  }
  static const char* value(const ::ric_board::get_devsRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::ric_board::get_devsRequest> should match 
// service_traits::DataType< ::ric_board::get_devs > 
template<>
struct DataType< ::ric_board::get_devsRequest>
{
  static const char* value()
  {
    return DataType< ::ric_board::get_devs >::value();
  }
  static const char* value(const ::ric_board::get_devsRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::ric_board::get_devsResponse> should match 
// service_traits::MD5Sum< ::ric_board::get_devs > 
template<>
struct MD5Sum< ::ric_board::get_devsResponse>
{
  static const char* value()
  {
    return MD5Sum< ::ric_board::get_devs >::value();
  }
  static const char* value(const ::ric_board::get_devsResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::ric_board::get_devsResponse> should match 
// service_traits::DataType< ::ric_board::get_devs > 
template<>
struct DataType< ::ric_board::get_devsResponse>
{
  static const char* value()
  {
    return DataType< ::ric_board::get_devs >::value();
  }
  static const char* value(const ::ric_board::get_devsResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // RIC_BOARD_MESSAGE_GET_DEVS_H
