// Generated by gencpp from file ric_board/GPS.msg
// DO NOT EDIT!


#ifndef RIC_BOARD_MESSAGE_GPS_H
#define RIC_BOARD_MESSAGE_GPS_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace ric_board
{
template <class ContainerAllocator>
struct GPS_
{
  typedef GPS_<ContainerAllocator> Type;

  GPS_()
    : Lat(0.0)
    , Lon(0.0)
    , Alt(0.0)
    , Sats(0)
    , HDOP(0)
    , Status(0)  {
    }
  GPS_(const ContainerAllocator& _alloc)
    : Lat(0.0)
    , Lon(0.0)
    , Alt(0.0)
    , Sats(0)
    , HDOP(0)
    , Status(0)  {
  (void)_alloc;
    }



   typedef double _Lat_type;
  _Lat_type Lat;

   typedef double _Lon_type;
  _Lon_type Lon;

   typedef float _Alt_type;
  _Alt_type Alt;

   typedef int16_t _Sats_type;
  _Sats_type Sats;

   typedef int16_t _HDOP_type;
  _HDOP_type HDOP;

   typedef int16_t _Status_type;
  _Status_type Status;




  typedef boost::shared_ptr< ::ric_board::GPS_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ric_board::GPS_<ContainerAllocator> const> ConstPtr;

}; // struct GPS_

typedef ::ric_board::GPS_<std::allocator<void> > GPS;

typedef boost::shared_ptr< ::ric_board::GPS > GPSPtr;
typedef boost::shared_ptr< ::ric_board::GPS const> GPSConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ric_board::GPS_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ric_board::GPS_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace ric_board

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'sensor_msgs': ['/opt/ros/indigo/share/sensor_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/indigo/share/geometry_msgs/cmake/../msg'], 'ric_board': ['/home/cc/ee106a/fa17/class/ee106a-aax/ros_workspaces/project/src/ric/ric_board/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::ric_board::GPS_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ric_board::GPS_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ric_board::GPS_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ric_board::GPS_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ric_board::GPS_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ric_board::GPS_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ric_board::GPS_<ContainerAllocator> >
{
  static const char* value()
  {
    return "b6b3576ebfcb04caffd96f3cf662f564";
  }

  static const char* value(const ::ric_board::GPS_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xb6b3576ebfcb04caULL;
  static const uint64_t static_value2 = 0xffd96f3cf662f564ULL;
};

template<class ContainerAllocator>
struct DataType< ::ric_board::GPS_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ric_board/GPS";
  }

  static const char* value(const ::ric_board::GPS_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ric_board::GPS_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 Lat\n\
float64 Lon\n\
float32 Alt\n\
int16 Sats\n\
int16 HDOP\n\
int16 Status\n\
\n\
";
  }

  static const char* value(const ::ric_board::GPS_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ric_board::GPS_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.Lat);
      stream.next(m.Lon);
      stream.next(m.Alt);
      stream.next(m.Sats);
      stream.next(m.HDOP);
      stream.next(m.Status);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GPS_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ric_board::GPS_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ric_board::GPS_<ContainerAllocator>& v)
  {
    s << indent << "Lat: ";
    Printer<double>::stream(s, indent + "  ", v.Lat);
    s << indent << "Lon: ";
    Printer<double>::stream(s, indent + "  ", v.Lon);
    s << indent << "Alt: ";
    Printer<float>::stream(s, indent + "  ", v.Alt);
    s << indent << "Sats: ";
    Printer<int16_t>::stream(s, indent + "  ", v.Sats);
    s << indent << "HDOP: ";
    Printer<int16_t>::stream(s, indent + "  ", v.HDOP);
    s << indent << "Status: ";
    Printer<int16_t>::stream(s, indent + "  ", v.Status);
  }
};

} // namespace message_operations
} // namespace ros

#endif // RIC_BOARD_MESSAGE_GPS_H
