// Generated by gencpp from file ric_board/imuCalib.msg
// DO NOT EDIT!


#ifndef RIC_BOARD_MESSAGE_IMUCALIB_H
#define RIC_BOARD_MESSAGE_IMUCALIB_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <ric_board/calibField.h>
#include <ric_board/calibField.h>
#include <ric_board/calibField.h>

namespace ric_board
{
template <class ContainerAllocator>
struct imuCalib_
{
  typedef imuCalib_<ContainerAllocator> Type;

  imuCalib_()
    : x()
    , y()
    , z()  {
    }
  imuCalib_(const ContainerAllocator& _alloc)
    : x(_alloc)
    , y(_alloc)
    , z(_alloc)  {
  (void)_alloc;
    }



   typedef  ::ric_board::calibField_<ContainerAllocator>  _x_type;
  _x_type x;

   typedef  ::ric_board::calibField_<ContainerAllocator>  _y_type;
  _y_type y;

   typedef  ::ric_board::calibField_<ContainerAllocator>  _z_type;
  _z_type z;




  typedef boost::shared_ptr< ::ric_board::imuCalib_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ric_board::imuCalib_<ContainerAllocator> const> ConstPtr;

}; // struct imuCalib_

typedef ::ric_board::imuCalib_<std::allocator<void> > imuCalib;

typedef boost::shared_ptr< ::ric_board::imuCalib > imuCalibPtr;
typedef boost::shared_ptr< ::ric_board::imuCalib const> imuCalibConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ric_board::imuCalib_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ric_board::imuCalib_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace ric_board

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'sensor_msgs': ['/opt/ros/indigo/share/sensor_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/indigo/share/geometry_msgs/cmake/../msg'], 'ric_board': ['/home/cc/ee106a/fa17/class/ee106a-aax/ros_workspaces/project/src/ric/ric_board/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::ric_board::imuCalib_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ric_board::imuCalib_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ric_board::imuCalib_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ric_board::imuCalib_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ric_board::imuCalib_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ric_board::imuCalib_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ric_board::imuCalib_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d267917841bb0bbefd54e631b648cc9b";
  }

  static const char* value(const ::ric_board::imuCalib_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd267917841bb0bbeULL;
  static const uint64_t static_value2 = 0xfd54e631b648cc9bULL;
};

template<class ContainerAllocator>
struct DataType< ::ric_board::imuCalib_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ric_board/imuCalib";
  }

  static const char* value(const ::ric_board::imuCalib_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ric_board::imuCalib_<ContainerAllocator> >
{
  static const char* value()
  {
    return "calibField x\n\
calibField y\n\
calibField z\n\
\n\
================================================================================\n\
MSG: ric_board/calibField\n\
float32 max\n\
float32 min\n\
\n\
float32 data\n\
\n\
float32 MAX_INIT = -100000.0\n\
float32 MIN_INIT = 100000.0\n\
";
  }

  static const char* value(const ::ric_board::imuCalib_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ric_board::imuCalib_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.x);
      stream.next(m.y);
      stream.next(m.z);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct imuCalib_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ric_board::imuCalib_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ric_board::imuCalib_<ContainerAllocator>& v)
  {
    s << indent << "x: ";
    s << std::endl;
    Printer< ::ric_board::calibField_<ContainerAllocator> >::stream(s, indent + "  ", v.x);
    s << indent << "y: ";
    s << std::endl;
    Printer< ::ric_board::calibField_<ContainerAllocator> >::stream(s, indent + "  ", v.y);
    s << indent << "z: ";
    s << std::endl;
    Printer< ::ric_board::calibField_<ContainerAllocator> >::stream(s, indent + "  ", v.z);
  }
};

} // namespace message_operations
} // namespace ros

#endif // RIC_BOARD_MESSAGE_IMUCALIB_H
