// Generated by gencpp from file ric_board/Named_Data.msg
// DO NOT EDIT!


#ifndef RIC_BOARD_MESSAGE_NAMED_DATA_H
#define RIC_BOARD_MESSAGE_NAMED_DATA_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace ric_board
{
template <class ContainerAllocator>
struct Named_Data_
{
  typedef Named_Data_<ContainerAllocator> Type;

  Named_Data_()
    : data(0.0)
    , name()  {
    }
  Named_Data_(const ContainerAllocator& _alloc)
    : data(0.0)
    , name(_alloc)  {
  (void)_alloc;
    }



   typedef float _data_type;
  _data_type data;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _name_type;
  _name_type name;




  typedef boost::shared_ptr< ::ric_board::Named_Data_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ric_board::Named_Data_<ContainerAllocator> const> ConstPtr;

}; // struct Named_Data_

typedef ::ric_board::Named_Data_<std::allocator<void> > Named_Data;

typedef boost::shared_ptr< ::ric_board::Named_Data > Named_DataPtr;
typedef boost::shared_ptr< ::ric_board::Named_Data const> Named_DataConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ric_board::Named_Data_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ric_board::Named_Data_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace ric_board

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'sensor_msgs': ['/opt/ros/indigo/share/sensor_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/indigo/share/geometry_msgs/cmake/../msg'], 'ric_board': ['/home/cc/ee106a/fa17/class/ee106a-aax/ros_workspaces/project/src/ric/ric_board/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::ric_board::Named_Data_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ric_board::Named_Data_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ric_board::Named_Data_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ric_board::Named_Data_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ric_board::Named_Data_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ric_board::Named_Data_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ric_board::Named_Data_<ContainerAllocator> >
{
  static const char* value()
  {
    return "14a4844ed23f715d29194ae2fc141a58";
  }

  static const char* value(const ::ric_board::Named_Data_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x14a4844ed23f715dULL;
  static const uint64_t static_value2 = 0x29194ae2fc141a58ULL;
};

template<class ContainerAllocator>
struct DataType< ::ric_board::Named_Data_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ric_board/Named_Data";
  }

  static const char* value(const ::ric_board::Named_Data_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ric_board::Named_Data_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 data\n\
string name\n\
\n\
\n\
";
  }

  static const char* value(const ::ric_board::Named_Data_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ric_board::Named_Data_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.data);
      stream.next(m.name);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Named_Data_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ric_board::Named_Data_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ric_board::Named_Data_<ContainerAllocator>& v)
  {
    s << indent << "data: ";
    Printer<float>::stream(s, indent + "  ", v.data);
    s << indent << "name: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.name);
  }
};

} // namespace message_operations
} // namespace ros

#endif // RIC_BOARD_MESSAGE_NAMED_DATA_H
