// Generated by gencpp from file ric_board/PPM.msg
// DO NOT EDIT!


#ifndef RIC_BOARD_MESSAGE_PPM_H
#define RIC_BOARD_MESSAGE_PPM_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace ric_board
{
template <class ContainerAllocator>
struct PPM_
{
  typedef PPM_<ContainerAllocator> Type;

  PPM_()
    : channels()  {
    }
  PPM_(const ContainerAllocator& _alloc)
    : channels(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector<float, typename ContainerAllocator::template rebind<float>::other >  _channels_type;
  _channels_type channels;




  typedef boost::shared_ptr< ::ric_board::PPM_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ric_board::PPM_<ContainerAllocator> const> ConstPtr;

}; // struct PPM_

typedef ::ric_board::PPM_<std::allocator<void> > PPM;

typedef boost::shared_ptr< ::ric_board::PPM > PPMPtr;
typedef boost::shared_ptr< ::ric_board::PPM const> PPMConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ric_board::PPM_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ric_board::PPM_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace ric_board

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'sensor_msgs': ['/opt/ros/indigo/share/sensor_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/indigo/share/geometry_msgs/cmake/../msg'], 'ric_board': ['/home/cc/ee106a/fa17/class/ee106a-aax/ros_workspaces/project/src/ric/ric_board/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::ric_board::PPM_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ric_board::PPM_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ric_board::PPM_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ric_board::PPM_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ric_board::PPM_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ric_board::PPM_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ric_board::PPM_<ContainerAllocator> >
{
  static const char* value()
  {
    return "eee9197417adede3e3b591abacc278fb";
  }

  static const char* value(const ::ric_board::PPM_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xeee9197417adede3ULL;
  static const uint64_t static_value2 = 0xe3b591abacc278fbULL;
};

template<class ContainerAllocator>
struct DataType< ::ric_board::PPM_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ric_board/PPM";
  }

  static const char* value(const ::ric_board::PPM_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ric_board::PPM_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32[] channels\n\
";
  }

  static const char* value(const ::ric_board::PPM_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ric_board::PPM_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.channels);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct PPM_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ric_board::PPM_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ric_board::PPM_<ContainerAllocator>& v)
  {
    s << indent << "channels[]" << std::endl;
    for (size_t i = 0; i < v.channels.size(); ++i)
    {
      s << indent << "  channels[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.channels[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // RIC_BOARD_MESSAGE_PPM_H
