// Generated by gencpp from file ric_board/Relay.msg
// DO NOT EDIT!


#ifndef RIC_BOARD_MESSAGE_RELAY_H
#define RIC_BOARD_MESSAGE_RELAY_H

#include <ros/service_traits.h>


#include <ric_board/RelayRequest.h>
#include <ric_board/RelayResponse.h>


namespace ric_board
{

struct Relay
{

typedef RelayRequest Request;
typedef RelayResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Relay
} // namespace ric_board


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::ric_board::Relay > {
  static const char* value()
  {
    return "9ba8ef602a660b19c32727fcd8cd5467";
  }

  static const char* value(const ::ric_board::Relay&) { return value(); }
};

template<>
struct DataType< ::ric_board::Relay > {
  static const char* value()
  {
    return "ric_board/Relay";
  }

  static const char* value(const ::ric_board::Relay&) { return value(); }
};


// service_traits::MD5Sum< ::ric_board::RelayRequest> should match 
// service_traits::MD5Sum< ::ric_board::Relay > 
template<>
struct MD5Sum< ::ric_board::RelayRequest>
{
  static const char* value()
  {
    return MD5Sum< ::ric_board::Relay >::value();
  }
  static const char* value(const ::ric_board::RelayRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::ric_board::RelayRequest> should match 
// service_traits::DataType< ::ric_board::Relay > 
template<>
struct DataType< ::ric_board::RelayRequest>
{
  static const char* value()
  {
    return DataType< ::ric_board::Relay >::value();
  }
  static const char* value(const ::ric_board::RelayRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::ric_board::RelayResponse> should match 
// service_traits::MD5Sum< ::ric_board::Relay > 
template<>
struct MD5Sum< ::ric_board::RelayResponse>
{
  static const char* value()
  {
    return MD5Sum< ::ric_board::Relay >::value();
  }
  static const char* value(const ::ric_board::RelayResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::ric_board::RelayResponse> should match 
// service_traits::DataType< ::ric_board::Relay > 
template<>
struct DataType< ::ric_board::RelayResponse>
{
  static const char* value()
  {
    return DataType< ::ric_board::Relay >::value();
  }
  static const char* value(const ::ric_board::RelayResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // RIC_BOARD_MESSAGE_RELAY_H
