# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from ric_robot/ric_status.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class ric_status(genpy.Message):
  _md5sum = "67d6e73ce3006094432bbce95b6807f9"
  _type = "ric_robot/ric_status"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """uint8 faults
float32 sensors_battery_voltage
float32 rover_battery_voltage
"""
  __slots__ = ['faults','sensors_battery_voltage','rover_battery_voltage']
  _slot_types = ['uint8','float32','float32']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       faults,sensors_battery_voltage,rover_battery_voltage

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(ric_status, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.faults is None:
        self.faults = 0
      if self.sensors_battery_voltage is None:
        self.sensors_battery_voltage = 0.
      if self.rover_battery_voltage is None:
        self.rover_battery_voltage = 0.
    else:
      self.faults = 0
      self.sensors_battery_voltage = 0.
      self.rover_battery_voltage = 0.

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_struct_B2f.pack(_x.faults, _x.sensors_battery_voltage, _x.rover_battery_voltage))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      end = 0
      _x = self
      start = end
      end += 9
      (_x.faults, _x.sensors_battery_voltage, _x.rover_battery_voltage,) = _struct_B2f.unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_struct_B2f.pack(_x.faults, _x.sensors_battery_voltage, _x.rover_battery_voltage))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      end = 0
      _x = self
      start = end
      end += 9
      (_x.faults, _x.sensors_battery_voltage, _x.rover_battery_voltage,) = _struct_B2f.unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
_struct_B2f = struct.Struct("<B2f")
