// Generated by gencpp from file ric_robot/home_elevator.msg
// DO NOT EDIT!


#ifndef RIC_ROBOT_MESSAGE_HOME_ELEVATOR_H
#define RIC_ROBOT_MESSAGE_HOME_ELEVATOR_H

#include <ros/service_traits.h>


#include <ric_robot/home_elevatorRequest.h>
#include <ric_robot/home_elevatorResponse.h>


namespace ric_robot
{

struct home_elevator
{

typedef home_elevatorRequest Request;
typedef home_elevatorResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct home_elevator
} // namespace ric_robot


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::ric_robot::home_elevator > {
  static const char* value()
  {
    return "44fb80a4df2631b52ba7ce4aeb2101f3";
  }

  static const char* value(const ::ric_robot::home_elevator&) { return value(); }
};

template<>
struct DataType< ::ric_robot::home_elevator > {
  static const char* value()
  {
    return "ric_robot/home_elevator";
  }

  static const char* value(const ::ric_robot::home_elevator&) { return value(); }
};


// service_traits::MD5Sum< ::ric_robot::home_elevatorRequest> should match 
// service_traits::MD5Sum< ::ric_robot::home_elevator > 
template<>
struct MD5Sum< ::ric_robot::home_elevatorRequest>
{
  static const char* value()
  {
    return MD5Sum< ::ric_robot::home_elevator >::value();
  }
  static const char* value(const ::ric_robot::home_elevatorRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::ric_robot::home_elevatorRequest> should match 
// service_traits::DataType< ::ric_robot::home_elevator > 
template<>
struct DataType< ::ric_robot::home_elevatorRequest>
{
  static const char* value()
  {
    return DataType< ::ric_robot::home_elevator >::value();
  }
  static const char* value(const ::ric_robot::home_elevatorRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::ric_robot::home_elevatorResponse> should match 
// service_traits::MD5Sum< ::ric_robot::home_elevator > 
template<>
struct MD5Sum< ::ric_robot::home_elevatorResponse>
{
  static const char* value()
  {
    return MD5Sum< ::ric_robot::home_elevator >::value();
  }
  static const char* value(const ::ric_robot::home_elevatorResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::ric_robot::home_elevatorResponse> should match 
// service_traits::DataType< ::ric_robot::home_elevator > 
template<>
struct DataType< ::ric_robot::home_elevatorResponse>
{
  static const char* value()
  {
    return DataType< ::ric_robot::home_elevator >::value();
  }
  static const char* value(const ::ric_robot::home_elevatorResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // RIC_ROBOT_MESSAGE_HOME_ELEVATOR_H
