// Generated by gencpp from file ric_robot/home_elevatorResponse.msg
// DO NOT EDIT!


#ifndef RIC_ROBOT_MESSAGE_HOME_ELEVATORRESPONSE_H
#define RIC_ROBOT_MESSAGE_HOME_ELEVATORRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace ric_robot
{
template <class ContainerAllocator>
struct home_elevatorResponse_
{
  typedef home_elevatorResponse_<ContainerAllocator> Type;

  home_elevatorResponse_()
    : ack(false)  {
    }
  home_elevatorResponse_(const ContainerAllocator& _alloc)
    : ack(false)  {
  (void)_alloc;
    }



   typedef uint8_t _ack_type;
  _ack_type ack;




  typedef boost::shared_ptr< ::ric_robot::home_elevatorResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ric_robot::home_elevatorResponse_<ContainerAllocator> const> ConstPtr;

}; // struct home_elevatorResponse_

typedef ::ric_robot::home_elevatorResponse_<std::allocator<void> > home_elevatorResponse;

typedef boost::shared_ptr< ::ric_robot::home_elevatorResponse > home_elevatorResponsePtr;
typedef boost::shared_ptr< ::ric_robot::home_elevatorResponse const> home_elevatorResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ric_robot::home_elevatorResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ric_robot::home_elevatorResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace ric_robot

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'ric_robot': ['/home/cc/ee106a/fa17/class/ee106a-aax/ros_workspaces/project/src/ric/ric_robot/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::ric_robot::home_elevatorResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ric_robot::home_elevatorResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ric_robot::home_elevatorResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ric_robot::home_elevatorResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ric_robot::home_elevatorResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ric_robot::home_elevatorResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ric_robot::home_elevatorResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "8f5729177853f34b146e2e57766d4dc2";
  }

  static const char* value(const ::ric_robot::home_elevatorResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x8f5729177853f34bULL;
  static const uint64_t static_value2 = 0x146e2e57766d4dc2ULL;
};

template<class ContainerAllocator>
struct DataType< ::ric_robot::home_elevatorResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ric_robot/home_elevatorResponse";
  }

  static const char* value(const ::ric_robot::home_elevatorResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ric_robot::home_elevatorResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool ack\n\
\n\
";
  }

  static const char* value(const ::ric_robot::home_elevatorResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ric_robot::home_elevatorResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.ack);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct home_elevatorResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ric_robot::home_elevatorResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ric_robot::home_elevatorResponse_<ContainerAllocator>& v)
  {
    s << indent << "ack: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.ack);
  }
};

} // namespace message_operations
} // namespace ros

#endif // RIC_ROBOT_MESSAGE_HOME_ELEVATORRESPONSE_H
