// Generated by gencpp from file ric_robot/relaysRequest.msg
// DO NOT EDIT!


#ifndef RIC_ROBOT_MESSAGE_RELAYSREQUEST_H
#define RIC_ROBOT_MESSAGE_RELAYSREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace ric_robot
{
template <class ContainerAllocator>
struct relaysRequest_
{
  typedef relaysRequest_<ContainerAllocator> Type;

  relaysRequest_()
    : ch1(false)
    , ch2(false)  {
    }
  relaysRequest_(const ContainerAllocator& _alloc)
    : ch1(false)
    , ch2(false)  {
  (void)_alloc;
    }



   typedef uint8_t _ch1_type;
  _ch1_type ch1;

   typedef uint8_t _ch2_type;
  _ch2_type ch2;




  typedef boost::shared_ptr< ::ric_robot::relaysRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ric_robot::relaysRequest_<ContainerAllocator> const> ConstPtr;

}; // struct relaysRequest_

typedef ::ric_robot::relaysRequest_<std::allocator<void> > relaysRequest;

typedef boost::shared_ptr< ::ric_robot::relaysRequest > relaysRequestPtr;
typedef boost::shared_ptr< ::ric_robot::relaysRequest const> relaysRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ric_robot::relaysRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ric_robot::relaysRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace ric_robot

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'ric_robot': ['/home/cc/ee106a/fa17/class/ee106a-aax/ros_workspaces/project/src/ric/ric_robot/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::ric_robot::relaysRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ric_robot::relaysRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ric_robot::relaysRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ric_robot::relaysRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ric_robot::relaysRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ric_robot::relaysRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ric_robot::relaysRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "1f11a3ed137a90a6662107bc18da38b6";
  }

  static const char* value(const ::ric_robot::relaysRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x1f11a3ed137a90a6ULL;
  static const uint64_t static_value2 = 0x662107bc18da38b6ULL;
};

template<class ContainerAllocator>
struct DataType< ::ric_robot::relaysRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ric_robot/relaysRequest";
  }

  static const char* value(const ::ric_robot::relaysRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ric_robot::relaysRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool ch1\n\
bool ch2\n\
";
  }

  static const char* value(const ::ric_robot::relaysRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ric_robot::relaysRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.ch1);
      stream.next(m.ch2);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct relaysRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ric_robot::relaysRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ric_robot::relaysRequest_<ContainerAllocator>& v)
  {
    s << indent << "ch1: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.ch1);
    s << indent << "ch2: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.ch2);
  }
};

} // namespace message_operations
} // namespace ros

#endif // RIC_ROBOT_MESSAGE_RELAYSREQUEST_H
