// Generated by gencpp from file ric_robot/relays.msg
// DO NOT EDIT!


#ifndef RIC_ROBOT_MESSAGE_RELAYS_H
#define RIC_ROBOT_MESSAGE_RELAYS_H

#include <ros/service_traits.h>


#include <ric_robot/relaysRequest.h>
#include <ric_robot/relaysResponse.h>


namespace ric_robot
{

struct relays
{

typedef relaysRequest Request;
typedef relaysResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct relays
} // namespace ric_robot


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::ric_robot::relays > {
  static const char* value()
  {
    return "2d8c02f55aad77e99ac4e150016bd681";
  }

  static const char* value(const ::ric_robot::relays&) { return value(); }
};

template<>
struct DataType< ::ric_robot::relays > {
  static const char* value()
  {
    return "ric_robot/relays";
  }

  static const char* value(const ::ric_robot::relays&) { return value(); }
};


// service_traits::MD5Sum< ::ric_robot::relaysRequest> should match 
// service_traits::MD5Sum< ::ric_robot::relays > 
template<>
struct MD5Sum< ::ric_robot::relaysRequest>
{
  static const char* value()
  {
    return MD5Sum< ::ric_robot::relays >::value();
  }
  static const char* value(const ::ric_robot::relaysRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::ric_robot::relaysRequest> should match 
// service_traits::DataType< ::ric_robot::relays > 
template<>
struct DataType< ::ric_robot::relaysRequest>
{
  static const char* value()
  {
    return DataType< ::ric_robot::relays >::value();
  }
  static const char* value(const ::ric_robot::relaysRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::ric_robot::relaysResponse> should match 
// service_traits::MD5Sum< ::ric_robot::relays > 
template<>
struct MD5Sum< ::ric_robot::relaysResponse>
{
  static const char* value()
  {
    return MD5Sum< ::ric_robot::relays >::value();
  }
  static const char* value(const ::ric_robot::relaysResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::ric_robot::relaysResponse> should match 
// service_traits::DataType< ::ric_robot::relays > 
template<>
struct DataType< ::ric_robot::relaysResponse>
{
  static const char* value()
  {
    return DataType< ::ric_robot::relays >::value();
  }
  static const char* value(const ::ric_robot::relaysResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // RIC_ROBOT_MESSAGE_RELAYS_H
