// Generated by gencpp from file ric_robot/ric_status.msg
// DO NOT EDIT!


#ifndef RIC_ROBOT_MESSAGE_RIC_STATUS_H
#define RIC_ROBOT_MESSAGE_RIC_STATUS_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace ric_robot
{
template <class ContainerAllocator>
struct ric_status_
{
  typedef ric_status_<ContainerAllocator> Type;

  ric_status_()
    : faults(0)
    , sensors_battery_voltage(0.0)
    , rover_battery_voltage(0.0)  {
    }
  ric_status_(const ContainerAllocator& _alloc)
    : faults(0)
    , sensors_battery_voltage(0.0)
    , rover_battery_voltage(0.0)  {
  (void)_alloc;
    }



   typedef uint8_t _faults_type;
  _faults_type faults;

   typedef float _sensors_battery_voltage_type;
  _sensors_battery_voltage_type sensors_battery_voltage;

   typedef float _rover_battery_voltage_type;
  _rover_battery_voltage_type rover_battery_voltage;




  typedef boost::shared_ptr< ::ric_robot::ric_status_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ric_robot::ric_status_<ContainerAllocator> const> ConstPtr;

}; // struct ric_status_

typedef ::ric_robot::ric_status_<std::allocator<void> > ric_status;

typedef boost::shared_ptr< ::ric_robot::ric_status > ric_statusPtr;
typedef boost::shared_ptr< ::ric_robot::ric_status const> ric_statusConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ric_robot::ric_status_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ric_robot::ric_status_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace ric_robot

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'ric_robot': ['/home/cc/ee106a/fa17/class/ee106a-aax/ros_workspaces/project/src/ric/ric_robot/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::ric_robot::ric_status_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ric_robot::ric_status_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ric_robot::ric_status_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ric_robot::ric_status_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ric_robot::ric_status_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ric_robot::ric_status_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ric_robot::ric_status_<ContainerAllocator> >
{
  static const char* value()
  {
    return "67d6e73ce3006094432bbce95b6807f9";
  }

  static const char* value(const ::ric_robot::ric_status_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x67d6e73ce3006094ULL;
  static const uint64_t static_value2 = 0x432bbce95b6807f9ULL;
};

template<class ContainerAllocator>
struct DataType< ::ric_robot::ric_status_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ric_robot/ric_status";
  }

  static const char* value(const ::ric_robot::ric_status_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ric_robot::ric_status_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint8 faults\n\
float32 sensors_battery_voltage\n\
float32 rover_battery_voltage\n\
";
  }

  static const char* value(const ::ric_robot::ric_status_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ric_robot::ric_status_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.faults);
      stream.next(m.sensors_battery_voltage);
      stream.next(m.rover_battery_voltage);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ric_status_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ric_robot::ric_status_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ric_robot::ric_status_<ContainerAllocator>& v)
  {
    s << indent << "faults: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.faults);
    s << indent << "sensors_battery_voltage: ";
    Printer<float>::stream(s, indent + "  ", v.sensors_battery_voltage);
    s << indent << "rover_battery_voltage: ";
    Printer<float>::stream(s, indent + "  ", v.rover_battery_voltage);
  }
};

} // namespace message_operations
} // namespace ros

#endif // RIC_ROBOT_MESSAGE_RIC_STATUS_H
