// Generated by gencpp from file ric_robot/ric_pan_tilt.msg
// DO NOT EDIT!


#ifndef RIC_ROBOT_MESSAGE_RIC_PAN_TILT_H
#define RIC_ROBOT_MESSAGE_RIC_PAN_TILT_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace ric_robot
{
template <class ContainerAllocator>
struct ric_pan_tilt_
{
  typedef ric_pan_tilt_<ContainerAllocator> Type;

  ric_pan_tilt_()
    : pan_angle(0.0)
    , tilt_angle(0.0)  {
    }
  ric_pan_tilt_(const ContainerAllocator& _alloc)
    : pan_angle(0.0)
    , tilt_angle(0.0)  {
  (void)_alloc;
    }



   typedef float _pan_angle_type;
  _pan_angle_type pan_angle;

   typedef float _tilt_angle_type;
  _tilt_angle_type tilt_angle;




  typedef boost::shared_ptr< ::ric_robot::ric_pan_tilt_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ric_robot::ric_pan_tilt_<ContainerAllocator> const> ConstPtr;

}; // struct ric_pan_tilt_

typedef ::ric_robot::ric_pan_tilt_<std::allocator<void> > ric_pan_tilt;

typedef boost::shared_ptr< ::ric_robot::ric_pan_tilt > ric_pan_tiltPtr;
typedef boost::shared_ptr< ::ric_robot::ric_pan_tilt const> ric_pan_tiltConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ric_robot::ric_pan_tilt_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ric_robot::ric_pan_tilt_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace ric_robot

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'ric_robot': ['/home/cc/ee106a/fa17/class/ee106a-aax/ros_workspaces/project/src/ric/ric_robot/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::ric_robot::ric_pan_tilt_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ric_robot::ric_pan_tilt_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ric_robot::ric_pan_tilt_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ric_robot::ric_pan_tilt_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ric_robot::ric_pan_tilt_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ric_robot::ric_pan_tilt_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ric_robot::ric_pan_tilt_<ContainerAllocator> >
{
  static const char* value()
  {
    return "f191de4d1f51ebd5f8f3b12305019bf6";
  }

  static const char* value(const ::ric_robot::ric_pan_tilt_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xf191de4d1f51ebd5ULL;
  static const uint64_t static_value2 = 0xf8f3b12305019bf6ULL;
};

template<class ContainerAllocator>
struct DataType< ::ric_robot::ric_pan_tilt_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ric_robot/ric_pan_tilt";
  }

  static const char* value(const ::ric_robot::ric_pan_tilt_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ric_robot::ric_pan_tilt_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 pan_angle\n\
float32 tilt_angle\n\
\n\
\n\
";
  }

  static const char* value(const ::ric_robot::ric_pan_tilt_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ric_robot::ric_pan_tilt_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.pan_angle);
      stream.next(m.tilt_angle);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ric_pan_tilt_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ric_robot::ric_pan_tilt_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ric_robot::ric_pan_tilt_<ContainerAllocator>& v)
  {
    s << indent << "pan_angle: ";
    Printer<float>::stream(s, indent + "  ", v.pan_angle);
    s << indent << "tilt_angle: ";
    Printer<float>::stream(s, indent + "  ", v.tilt_angle);
  }
};

} // namespace message_operations
} // namespace ros

#endif // RIC_ROBOT_MESSAGE_RIC_PAN_TILT_H
