// Generated by gencpp from file ric_robot/ric_calibRequest.msg
// DO NOT EDIT!


#ifndef RIC_ROBOT_MESSAGE_RIC_CALIBREQUEST_H
#define RIC_ROBOT_MESSAGE_RIC_CALIBREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace ric_robot
{
template <class ContainerAllocator>
struct ric_calibRequest_
{
  typedef ric_calibRequest_<ContainerAllocator> Type;

  ric_calibRequest_()
    : com(0)  {
    }
  ric_calibRequest_(const ContainerAllocator& _alloc)
    : com(0)  {
  (void)_alloc;
    }



   typedef int16_t _com_type;
  _com_type com;




  typedef boost::shared_ptr< ::ric_robot::ric_calibRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ric_robot::ric_calibRequest_<ContainerAllocator> const> ConstPtr;

}; // struct ric_calibRequest_

typedef ::ric_robot::ric_calibRequest_<std::allocator<void> > ric_calibRequest;

typedef boost::shared_ptr< ::ric_robot::ric_calibRequest > ric_calibRequestPtr;
typedef boost::shared_ptr< ::ric_robot::ric_calibRequest const> ric_calibRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ric_robot::ric_calibRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ric_robot::ric_calibRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace ric_robot

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'ric_robot': ['/home/cc/ee106a/fa17/class/ee106a-aax/ros_workspaces/project/src/ric/ric_robot/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::ric_robot::ric_calibRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ric_robot::ric_calibRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ric_robot::ric_calibRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ric_robot::ric_calibRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ric_robot::ric_calibRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ric_robot::ric_calibRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ric_robot::ric_calibRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "0dce049a176069675a0c664de0822e2c";
  }

  static const char* value(const ::ric_robot::ric_calibRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x0dce049a17606967ULL;
  static const uint64_t static_value2 = 0x5a0c664de0822e2cULL;
};

template<class ContainerAllocator>
struct DataType< ::ric_robot::ric_calibRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ric_robot/ric_calibRequest";
  }

  static const char* value(const ::ric_robot::ric_calibRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ric_robot::ric_calibRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int16 com\n\
";
  }

  static const char* value(const ::ric_robot::ric_calibRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ric_robot::ric_calibRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.com);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ric_calibRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ric_robot::ric_calibRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ric_robot::ric_calibRequest_<ContainerAllocator>& v)
  {
    s << indent << "com: ";
    Printer<int16_t>::stream(s, indent + "  ", v.com);
  }
};

} // namespace message_operations
} // namespace ros

#endif // RIC_ROBOT_MESSAGE_RIC_CALIBREQUEST_H
