// Generated by gencpp from file ric_robot/set_odom.msg
// DO NOT EDIT!


#ifndef RIC_ROBOT_MESSAGE_SET_ODOM_H
#define RIC_ROBOT_MESSAGE_SET_ODOM_H

#include <ros/service_traits.h>


#include <ric_robot/set_odomRequest.h>
#include <ric_robot/set_odomResponse.h>


namespace ric_robot
{

struct set_odom
{

typedef set_odomRequest Request;
typedef set_odomResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct set_odom
} // namespace ric_robot


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::ric_robot::set_odom > {
  static const char* value()
  {
    return "a130bc60ee6513855dc62ea83fcc5b20";
  }

  static const char* value(const ::ric_robot::set_odom&) { return value(); }
};

template<>
struct DataType< ::ric_robot::set_odom > {
  static const char* value()
  {
    return "ric_robot/set_odom";
  }

  static const char* value(const ::ric_robot::set_odom&) { return value(); }
};


// service_traits::MD5Sum< ::ric_robot::set_odomRequest> should match 
// service_traits::MD5Sum< ::ric_robot::set_odom > 
template<>
struct MD5Sum< ::ric_robot::set_odomRequest>
{
  static const char* value()
  {
    return MD5Sum< ::ric_robot::set_odom >::value();
  }
  static const char* value(const ::ric_robot::set_odomRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::ric_robot::set_odomRequest> should match 
// service_traits::DataType< ::ric_robot::set_odom > 
template<>
struct DataType< ::ric_robot::set_odomRequest>
{
  static const char* value()
  {
    return DataType< ::ric_robot::set_odom >::value();
  }
  static const char* value(const ::ric_robot::set_odomRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::ric_robot::set_odomResponse> should match 
// service_traits::MD5Sum< ::ric_robot::set_odom > 
template<>
struct MD5Sum< ::ric_robot::set_odomResponse>
{
  static const char* value()
  {
    return MD5Sum< ::ric_robot::set_odom >::value();
  }
  static const char* value(const ::ric_robot::set_odomResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::ric_robot::set_odomResponse> should match 
// service_traits::DataType< ::ric_robot::set_odom > 
template<>
struct DataType< ::ric_robot::set_odomResponse>
{
  static const char* value()
  {
    return DataType< ::ric_robot::set_odom >::value();
  }
  static const char* value(const ::ric_robot::set_odomResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // RIC_ROBOT_MESSAGE_SET_ODOM_H
