// Generated by gencpp from file ric_robot/set_elevator.msg
// DO NOT EDIT!


#ifndef RIC_ROBOT_MESSAGE_SET_ELEVATOR_H
#define RIC_ROBOT_MESSAGE_SET_ELEVATOR_H

#include <ros/service_traits.h>


#include <ric_robot/set_elevatorRequest.h>
#include <ric_robot/set_elevatorResponse.h>


namespace ric_robot
{

struct set_elevator
{

typedef set_elevatorRequest Request;
typedef set_elevatorResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct set_elevator
} // namespace ric_robot


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::ric_robot::set_elevator > {
  static const char* value()
  {
    return "ceff98cb9fd261360b9286820475eab6";
  }

  static const char* value(const ::ric_robot::set_elevator&) { return value(); }
};

template<>
struct DataType< ::ric_robot::set_elevator > {
  static const char* value()
  {
    return "ric_robot/set_elevator";
  }

  static const char* value(const ::ric_robot::set_elevator&) { return value(); }
};


// service_traits::MD5Sum< ::ric_robot::set_elevatorRequest> should match 
// service_traits::MD5Sum< ::ric_robot::set_elevator > 
template<>
struct MD5Sum< ::ric_robot::set_elevatorRequest>
{
  static const char* value()
  {
    return MD5Sum< ::ric_robot::set_elevator >::value();
  }
  static const char* value(const ::ric_robot::set_elevatorRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::ric_robot::set_elevatorRequest> should match 
// service_traits::DataType< ::ric_robot::set_elevator > 
template<>
struct DataType< ::ric_robot::set_elevatorRequest>
{
  static const char* value()
  {
    return DataType< ::ric_robot::set_elevator >::value();
  }
  static const char* value(const ::ric_robot::set_elevatorRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::ric_robot::set_elevatorResponse> should match 
// service_traits::MD5Sum< ::ric_robot::set_elevator > 
template<>
struct MD5Sum< ::ric_robot::set_elevatorResponse>
{
  static const char* value()
  {
    return MD5Sum< ::ric_robot::set_elevator >::value();
  }
  static const char* value(const ::ric_robot::set_elevatorResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::ric_robot::set_elevatorResponse> should match 
// service_traits::DataType< ::ric_robot::set_elevator > 
template<>
struct DataType< ::ric_robot::set_elevatorResponse>
{
  static const char* value()
  {
    return DataType< ::ric_robot::set_elevator >::value();
  }
  static const char* value(const ::ric_robot::set_elevatorResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // RIC_ROBOT_MESSAGE_SET_ELEVATOR_H
